### This notebook is used to verify if the random generated scanpath used for baseline is valid

In [39]:
from tools.auxiliary import parse_single_experiment, build_vector, gen_random_fixations
import numpy as np
import multimatch_gaze as m

exp_1 = ("102", "2")
eye_event_1, samples_1 = parse_single_experiment(exp_1[0])
vec_1 = build_vector(exp_1, eye_event_1).rename(columns={'x0': 'start_x', 'y0': 'start_y'})

exp_2 = ("104", "2")
eye_event_2, samples_2 = parse_single_experiment(exp_2[0])
vec_2 = build_vector(exp_2, eye_event_2).rename(columns={'x0': 'start_x', 'y0': 'start_y'})

original_score = m.docomparison(vec_1, vec_2, screensize=[1920, 1080])

k = 100

Parsing experiment: 102 from file: 102_rawdata.tsv
parsing file: 102_rawdata.tsv
Parsing experiment: 104 from file: 104_rawdata.tsv
parsing file: 104_rawdata.tsv


In [43]:
print(original_score)
isinstance(original_score, list)
len(original_score)

[0.9922383707940517, 0.5092314274105434, 0.9850109578322774, 0.5726370116743846, 0.00387460373370907]


5

In [ ]:
rv_list_1 = []
for i in range(k):
    random_fixations = gen_random_fixations(len(vec_1))
    rv_list_1.append(random_fixations)

rv_list_2 = []
for i in range(k):
    random_fixations = gen_random_fixations(len(vec_2))
    rv_list_2.append(random_fixations)

rv_scores = []

# p-value calculation
# p_values = 0
# for i in 
# print("P-values:\n", p_values)

             x0           y0  duration
0   1183.150687  1014.941718  0.909306
1   1138.345400   328.708393  1.222733
2    628.704568   123.940390  1.092209
3    270.881385  1006.948558  1.335922
4   1315.779407   561.268459  1.020513
5    429.721531   817.215183  0.822211
6    684.799474   865.404321  1.271091
7   1719.539699   551.003343  1.348636
8    524.826458   853.562696  1.161974
9   1231.968389   147.437917  1.347064
10   625.968514   973.243826  0.810597
11   959.709681   409.587278  1.108623
12   877.129936   151.187233  1.261845
13  1376.819413   452.248415  1.348062
14  1561.294075   244.573541  1.232161
15  1705.290572   323.986344  1.251036
16   645.733614   312.993788  1.273868
17   697.715924   564.386520  1.281486
Mean of random vectors:
 [[ 980.1702275   537.36274842    1.13072606]
 [ 976.12390026  546.9588909     1.13617597]
 [ 992.66540481  579.50074315    1.15612273]
 [ 976.21070211  533.81020184    1.13666907]
 [ 986.89183405  484.15729626    1.15040016]
 [ 986.99

TypeError: unsupported operand type(s) for /: 'generator' and 'int'